// Generated by dojo-bindgen on Fri, 26 Jul 2024 01:44:15 +0000. Do not modify this file manually.
import { Account } from "starknet";
import {
    Clause,
    Client,
    ModelClause,
    createClient,
    valueToToriiValueAndOperator,
} from "@dojoengine/torii-client";
import {
    LOCAL_KATANA,
    LOCAL_RELAY,
    LOCAL_TORII,
    createManifestFromJson,
} from "@dojoengine/core";

// Type definition for `dojo_starter::models::game::Game` struct
export interface Game {
    game_id: number;
    players: string[];
    tile_length: number;
    turn_player: string;
    status: Status;
}

// Type definition for `core::byte_array::ByteArray` struct
export interface ByteArray {
    data: string[];
    pending_word: string;
    pending_word_len: number;
}

// Type definition for `core::option::Option::<core::integer::u32>` enum
type Option<A> = { type: 'Some'; data: A; } | { type: 'None'; }
// Type definition for `dojo_starter::models::game::Status` enum
type Status = { type: 'Pending'; } | { type: 'Active'; } | { type: 'Completed'; }

// Type definition for `dojo_starter::models::position::Tile` struct
export interface Tile {
    game_id: number;
    number: number;
    effect: Effect;
}

// Type definition for `dojo_starter::models::position::Effect` enum
type Effect = { type: 'None'; } | { type: 'Forward'; data: number; } | { type: 'Backward'; data: number; }

// Type definition for `dojo_starter::systems::actions::actions::Moved` struct
export interface Moved {
    player: string;
    amt: number;
}


// Type definition for `dojo_starter::models::position::Position` struct
export interface Position {
    game_id: number;
    player: string;
    tile: number;
}


class BaseCalls {
    contractAddress: string;
    account?: Account;

    constructor(contractAddress: string, account?: Account) {
        this.account = account;
        this.contractAddress = contractAddress;
    }

    async execute(entrypoint: string, calldata: any[] = []): Promise<void> {
        if (!this.account) {
            throw new Error("No account set to interact with dojo_starter");
        }

        await this.account.execute(
            {
                contractAddress: this.contractAddress,
                entrypoint,
                calldata,
            },
            undefined,
            {
                maxFee: 0,
            }
        );
    }
}

class ActionsCalls extends BaseCalls {
    constructor(contractAddress: string, account?: Account) {
        super(contractAddress, account);
    }

    async spawn(): Promise<void> {
        try {
            await this.execute("spawn", [])
        } catch (error) {
            console.error("Error executing spawn:", error);
            throw error;
        }
    }

    async move(): Promise<void> {
        try {
            await this.execute("move", [])
        } catch (error) {
            console.error("Error executing move:", error);
            throw error;
        }
    }

    async createGame(): Promise<void> {
        try {
            await this.execute("create_game", [])
        } catch (error) {
            console.error("Error executing createGame:", error);
            throw error;
        }
    }

    async joinGame(game_id: number): Promise<void> {
        try {
            await this.execute("join_game", [game_id])
        } catch (error) {
            console.error("Error executing joinGame:", error);
            throw error;
        }
    }

    async startGame(game_id: number): Promise<void> {
        try {
            await this.execute("start_game", [game_id])
        } catch (error) {
            console.error("Error executing startGame:", error);
            throw error;
        }
    }

    async contractName(): Promise<void> {
        try {
            await this.execute("contract_name", [])
        } catch (error) {
            console.error("Error executing contractName:", error);
            throw error;
        }
    }

    async namespace(): Promise<void> {
        try {
            await this.execute("namespace", [])
        } catch (error) {
            console.error("Error executing namespace:", error);
            throw error;
        }
    }

    async tag(): Promise<void> {
        try {
            await this.execute("tag", [])
        } catch (error) {
            console.error("Error executing tag:", error);
            throw error;
        }
    }

    async nameHash(): Promise<void> {
        try {
            await this.execute("name_hash", [])
        } catch (error) {
            console.error("Error executing nameHash:", error);
            throw error;
        }
    }

    async namespaceHash(): Promise<void> {
        try {
            await this.execute("namespace_hash", [])
        } catch (error) {
            console.error("Error executing namespaceHash:", error);
            throw error;
        }
    }

    async selector(): Promise<void> {
        try {
            await this.execute("selector", [])
        } catch (error) {
            console.error("Error executing selector:", error);
            throw error;
        }
    }

    async dojoInit(): Promise<void> {
        try {
            await this.execute("dojo_init", [])
        } catch (error) {
            console.error("Error executing dojoInit:", error);
            throw error;
        }
    }
}

type Query = Partial<{
    Game: ModelClause<Game>;
    Tile: ModelClause<Tile>;
    Moved: ModelClause<Moved>;
    Position: ModelClause<Position>;
}>;

type ResultMapping = {
    Game: Game;
    Tile: Tile;
    Moved: Moved;
    Position: Position;
};

type QueryResult<T extends Query> = {
    [K in keyof T]: K extends keyof ResultMapping ? ResultMapping[K] : never;
};

// Only supports a single model for now, since torii doesn't support multiple models
// And inside that single model, there's only support for a single query.
function convertQueryToToriiClause(query: Query): Clause | undefined {
    const [model, clause] = Object.entries(query)[0];

    if (Object.keys(clause).length === 0) {
        return undefined;
    }

    const clauses: Clause[] = Object.entries(clause).map(([key, value]) => {
        return {
            Member: {
                model,
                member: key,
                ...valueToToriiValueAndOperator(value),
            },
        } satisfies Clause;
    });

    return clauses[0];
}
type GeneralParams = {
    toriiUrl?: string;
    relayUrl?: string;
    account?: Account;
};

type InitialParams = GeneralParams &
    (
        | {
                rpcUrl?: string;
                worldAddress: string;
                actionsAddress: string;
            }
        | {
                manifest: any;
            }
    );

export class DojoStarter {
    rpcUrl: string;
    toriiUrl: string;
    toriiPromise: Promise<Client>;
    relayUrl: string;
    worldAddress: string;
    private _account?: Account;
    actions: ActionsCalls;
    actionsAddress: string;

    constructor(params: InitialParams) {
        if ("manifest" in params) {
            const config = createManifestFromJson(params.manifest);
            this.rpcUrl = config.world.metadata.rpc_url;
            this.worldAddress = config.world.address;

            const actionsAddress = config.contracts.find(
                (contract) =>
                    contract.name === "dojo_starter::systems::actions::actions"
            )?.address;

            if (!actionsAddress) {
                throw new Error("No actions contract found in the manifest");
            }

            this.actionsAddress = actionsAddress;
        } else {
            this.rpcUrl = params.rpcUrl || LOCAL_KATANA;
            this.worldAddress = params.worldAddress;
            this.actionsAddress = params.actionsAddress;
        }
        this.toriiUrl = params.toriiUrl || LOCAL_TORII;
        this.relayUrl = params.relayUrl || LOCAL_RELAY;
        this._account = params.account;
        this.actions = new ActionsCalls(this.actionsAddress, this._account);

        this.toriiPromise = createClient([], {
            rpcUrl: this.rpcUrl,
            toriiUrl: this.toriiUrl,
            worldAddress: this.worldAddress,
            relayUrl: this.relayUrl,
        });
    }

    get account(): Account | undefined {
        return this._account;
    }

    set account(account: Account) {
        this._account = account;
        this.actions = new ActionsCalls(this.actionsAddress, this._account);
    }

    async query<T extends Query>(query: T, limit = 10, offset = 0) {
        const torii = await this.toriiPromise;

        return {
            torii,
            findEntities: async () => this.findEntities(query, limit, offset),
        };
    }

    async findEntities<T extends Query>(query: T, limit = 10, offset = 0) {
        const torii = await this.toriiPromise;

        const clause = convertQueryToToriiClause(query);

        const toriiResult = await torii.getEntities({
            limit,
            offset,
            clause,
        });

        return toriiResult as Record<string, QueryResult<T>>;
    }

    async findEntity<T extends Query>(query: T) {
        const result = await this.findEntities(query, 1);

        if (Object.values(result).length === 0) {
            return undefined;
        }

        return Object.values(result)[0] as QueryResult<T>;
    }
}