[world]
kind = "WorldContract"
class_hash = "0x76ced5a15cb43c7be7176cff4779cd57c56638a46ddf2c9da709d22298c5e5a"
original_class_hash = "0x76ced5a15cb43c7be7176cff4779cd57c56638a46ddf2c9da709d22298c5e5a"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x42e172247714a480a40121c97c13acb1338e6cc8948b5ae23f5d7d53cd26338"
transaction_hash = "0x27be65ab7dbbeee4fc4c4385a7ce882ba6ad38766f0b53904a7a989d94abf22"
block_number = 3
seed = "dojo_examples"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x46e6c059917c1024b714d472d4c93e53e45a151066557847fe5d0183a9186a3"
class_hash = "0x360018297e3304ebeb919f49378f8f437a28c0bc6034c8c9e48c23295ef57bb"
original_class_hash = "0x360018297e3304ebeb919f49378f8f437a28c0bc6034c8c9e48c23295ef57bb"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/ok-actions-27182f10.json"
reads = []
writes = [
    "ok-Game",
    "ok-Position",
    "ok-Tile",
    "ok-Pending",
    "ok-Moved",
]
init_calldata = []
tag = "ok-actions"
manifest_name = "ok-actions-27182f10"

[[contracts]]
kind = "DojoContract"
address = "0x5589faeaa71c1912caa46d90c81a864f26cdb4c7f734ccaa650b47e1bad96c"
class_hash = "0x76290aa2d63988b496363f83af7f14a4fd65e361a17b27fcc81d93882941e04"
original_class_hash = "0x76290aa2d63988b496363f83af7f14a4fd65e361a17b27fcc81d93882941e04"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/ok-matchmaking-7ba13579.json"
reads = []
writes = [
    "ok-Game",
    "ok-Position",
]
init_calldata = []
tag = "ok-matchmaking"
manifest_name = "ok-matchmaking-7ba13579"

[[models]]
kind = "DojoModel"
class_hash = "0x6e4ccdf50299459ab22f5ea0e5298a57ff2db58cc0e77c5805c1d8c719c8ead"
original_class_hash = "0x6e4ccdf50299459ab22f5ea0e5298a57ff2db58cc0e77c5805c1d8c719c8ead"
abi = "manifests/dev/deployment/abis/models/ok-Game-57e3f47c.json"
tag = "ok-Game"
manifest_name = "ok-Game-57e3f47c"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "players"
type = "Array<ContractAddress>"
key = false

[[models.members]]
name = "tile_length"
type = "u8"
key = false

[[models.members]]
name = "turn_player"
type = "ContractAddress"
key = false

[[models.members]]
name = "status"
type = "Status"
key = false

[[models.members]]
name = "phase"
type = "TurnPhase"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x19e278ad11928dbb06799467aebf6caf3687766c3443c5f564fb57f23671bb5"
original_class_hash = "0x19e278ad11928dbb06799467aebf6caf3687766c3443c5f564fb57f23671bb5"
abi = "manifests/dev/deployment/abis/models/ok-Moved-5cd98501.json"
tag = "ok-Moved"
manifest_name = "ok-Moved-5cd98501"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "amt"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x52dc797642775f17c4cb0dcb016635011576a8610c9730418654d681263e51c"
original_class_hash = "0x52dc797642775f17c4cb0dcb016635011576a8610c9730418654d681263e51c"
abi = "manifests/dev/deployment/abis/models/ok-Pending-5c5c71db.json"
tag = "ok-Pending"
manifest_name = "ok-Pending-5c5c71db"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "effect"
type = "Effect"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x24a174eaa2209ea3d93757cd4913bbd72599f3d6d88340e6f4619247ead837d"
original_class_hash = "0x24a174eaa2209ea3d93757cd4913bbd72599f3d6d88340e6f4619247ead837d"
abi = "manifests/dev/deployment/abis/models/ok-Position-54881f2f.json"
tag = "ok-Position"
manifest_name = "ok-Position-54881f2f"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "tile"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2fb5699e10c7e793cfb9562d276225e4d564b416e8bb3a2dc3116bf0ddf2019"
original_class_hash = "0x2fb5699e10c7e793cfb9562d276225e4d564b416e8bb3a2dc3116bf0ddf2019"
abi = "manifests/dev/deployment/abis/models/ok-Tile-fcb463a2.json"
tag = "ok-Tile"
manifest_name = "ok-Tile-fcb463a2"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "number"
type = "u8"
key = true

[[models.members]]
name = "effect"
type = "Effect"
key = false
