kind = "DojoModel"
class_hash = "0x322d17c0504db5b267f05ed76d805c43616e3ff519d4d928a9061db03a0c297"
original_class_hash = "0x322d17c0504db5b267f05ed76d805c43616e3ff519d4d928a9061db03a0c297"
abi = "manifests/dev/base/abis/models/ok-Game-57e3f47c.json"
tag = "ok-Game"
manifest_name = "ok-Game-57e3f47c"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "players"
type = "Array<ContractAddress>"
key = false

[[members]]
name = "tile_length"
type = "u8"
key = false

[[members]]
name = "turn_player"
type = "ContractAddress"
key = false

[[members]]
name = "active_effects"
type = "Array<Effect>"
key = false

[[members]]
name = "status"
type = "Status"
key = false

[[members]]
name = "phase"
type = "TurnPhase"
key = false
