kind = "DojoModel"
class_hash = "0x19e278ad11928dbb06799467aebf6caf3687766c3443c5f564fb57f23671bb5"
original_class_hash = "0x19e278ad11928dbb06799467aebf6caf3687766c3443c5f564fb57f23671bb5"
abi = "manifests/dev/base/abis/models/ok-Moved-5cd98501.json"
tag = "ok-Moved"
manifest_name = "ok-Moved-5cd98501"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "amt"
type = "u8"
key = false
