kind = "DojoModel"
class_hash = "0x19406e5aed2d1c2fa9b5197885618accb4f620e8124da8c27e6ab0a9811f645"
original_class_hash = "0x19406e5aed2d1c2fa9b5197885618accb4f620e8124da8c27e6ab0a9811f645"
abi = "manifests/dev/base/abis/models/ok-Pending-5c5c71db.json"
tag = "ok-Pending"
manifest_name = "ok-Pending-5c5c71db"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "effect"
type = "Effect"
key = false
