kind = "DojoModel"
class_hash = "0x45e70ba44841fbc28d8304b54e25ff17429734a2e55b487258fce5d76ebd30c"
original_class_hash = "0x45e70ba44841fbc28d8304b54e25ff17429734a2e55b487258fce5d76ebd30c"
abi = "manifests/dev/base/abis/models/ok-Tile-fcb463a2.json"
tag = "ok-Tile"
manifest_name = "ok-Tile-fcb463a2"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "number"
type = "u8"
key = true

[[members]]
name = "effect"
type = "Effect"
key = false
