kind = "DojoContract"
class_hash = "0x6652fc6681624ff0b36f743278e88e26dd6ef255cbd85ca679256f8c9efd63e"
original_class_hash = "0x6652fc6681624ff0b36f743278e88e26dd6ef255cbd85ca679256f8c9efd63e"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/ok-actions-27182f10.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "ok-actions"
manifest_name = "ok-actions-27182f10"
