kind = "DojoContract"
class_hash = "0x7502cb9d3cbf44db35f3369d445b6b8a0ce104e94efcf178485c121cd3c7c21"
original_class_hash = "0x7502cb9d3cbf44db35f3369d445b6b8a0ce104e94efcf178485c121cd3c7c21"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/ok-actions-27182f10.json"
reads = []
writes = []
init_calldata = []
tag = "ok-actions"
systems = [
    "move",
    "resolve_turn",
    "set_pending_effect",
]
manifest_name = "ok-actions-27182f10"
