kind = "DojoContract"
class_hash = "0x34a08c568a3023b11eca5d6c5cdead310d499d8e6b4795847a7179147b1eeca"
original_class_hash = "0x34a08c568a3023b11eca5d6c5cdead310d499d8e6b4795847a7179147b1eeca"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/ok-actions-27182f10.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "ok-actions"
manifest_name = "ok-actions-27182f10"
